trigger:
- master

variables:

  # Azure Resource Manager service connection 
  azureSubscription: 'vvp-pipeline-service-connection'

  # Agent VM image name: Windows is needed by AzureFileCopy@3
  vmImageName: 'windows-latest'

  # DEBUG
  system.debug: true

  # Ververica Platform related settings
  vvpNamespace: 'default'
  vvpDeploymentTarget: ''
  servicePrincipal: 'http://vvp-pipeline-demo-service-principal'
  tenantId: '2925ee25-3bd0-402a-88f1-69307e6a39f3'
  keyVault: 'vvp-pipeline-keyvault'
  servicePrincipalSecretName: 'vvp-pipeline-demo-service-principal-password'
  vvpResourceGroup: 'vvp-pipeline-demo'
  vvpClusterName: 'vvp-pipeline-cluster'
  vvpKubernetesNamespace: 'vvp'


stages:

### Build stage
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndPublish
    displayName: Package and Publish

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: Stage job jar
      inputs:
        SourceFolder: 'target'
        Contents: 'wiki-*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifactName: JobJar

### Deploy stage
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DownloadAndDeploy
      displayName: Download and deploy
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download artifacts
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(build.artifactstagingdirectory)' 

      - task: AzureFileCopy@3
        displayName: Deploy to blob storage
        inputs:
          sourcePath: '$(build.artifactstagingdirectory)' 
          azureSubscription: '$(azureSubscription)'
          destination: azureBlob
          storage: vvppipelinestorage
          containerName: vvp-pipeline-artifacts
          BlobPrefix: 'artifacts/namespaces/$(vvpNamespace)'

- stage: Submit
  displayName: Submit stage
  jobs:
    - job: SubmitFlinkJob
      displayName: Submit flink job
      steps:
        - task: KubectlInstaller@0
          displayName: Install kubectl
          inputs: 
            kubectlVersion: 1.15.0

        - task: AzureKeyVault@1
          inputs:
            azureSubscription: '$(azureSubscription)'
            KeyVaultName: '$(keyVault)'
            SecretsFilter: '$(servicePrincipalSecretName)'

        - script: az login --service-principal -u $(servicePrincipal) -p $(servicePrincipalSecretName)  --tenant $(tenantId)
        - script: az aks get-credentials --resource-group $(vvpResourceGroup) --name $(vvpCluster)
        - script: kubectl port-forward service/vvp-ververica-platform 8080:80 --namespace $(vvpKubernetesNamespace) &
        # - script: |
        #     curl -X PATCH "http://localhost:8080/api/v1/namespaces/default/deployments/4ebe37b7-79af-40a2-a0d5-05976f062e52" -H "accept: application/yaml" -H "Content-Type: application/yaml" -d '
        #     ---
        #     kind: Deployment
        #     apiVersion: v1
        #     spec:
        #       state: CANCELLED
        #     '