trigger:
- master

variables:

  # Azure Resource Manager service connection 
  azureSubscription: 'vvp-pipeline-service-connection'

  # Agent VM image name
  # Except the depoly stage which uses a Windows image as it is required by AzureFileCopy@3 task
  vmImageName: 'ubuntu-latest'

  # DEBUG
  system.debug: true

  # Azure resources
  resourceGroup: 'vvp-pipeline-demo'
  servicePrincipal: 'http://vvp-pipeline-service-principal'
  keyVault: 'vvp-pipeline-keyvault'
  storageAccount: 'vvppipelinestorage'
  blobContainer: 'vvp-pipeline-container'

  # Kubernetes
  kubernetesCluster: 'vvp-pipeline-cluster'
  kubernetesNamespace: 'vvp'

  # Ververica Platform
  vvpNamespace: 'default'
  vvpDeploymentTarget: '6232cc84-7aa3-4524-b3a8-36cab7203c47'
  vvpJobJarPrefix: 'vvp-pipeline-demo'

  # misc.
  delayMinutes: 2

stages:

# Build stage
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndPublish
    displayName: Package and publish

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: Stage artifacts
      inputs:
        SourceFolder: 'target'
        Contents: '$(vvpJobJarPrefix)-*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)/artifacts'

    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: '$(build.artifactstagingdirectory)/artifacts'
        artifactName: JobJar

# Deploy stage
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
    - job: DownloadAndDeploy
      displayName: Download and deploy

      # We use a windows image here because AzureFileCopy@3 runs only on Windows
      pool:
        vmImage: 'windows-latest'

      steps:

      - task: DownloadPipelineArtifact@2
        displayName: Download artifacts
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(build.artifactstagingdirectory)/artifacts' 

      - task: AzureFileCopy@3
        displayName: Deploy to blob storage
        inputs:
          sourcePath: '$(build.artifactstagingdirectory)/artifacts' 
          azureSubscription: '$(azureSubscription)'
          destination: 'AzureBlob'
          storage: '$(storageAccount)'
          containerName: '$(blobContainer)'
          BlobPrefix: 'artifacts/namespaces/$(vvpNamespace)'

# Submit stage
- stage: Submit
  displayName: Submit stage
  dependsOn: Deploy
  condition: succeeded()

  jobs:
    - job: SubmitFlinkJob
      displayName: Submit flink job

      pool:
        vmImage: $(vmImageName)

      steps:

        - task: KubectlInstaller@0
          displayName: Install kubectl
          inputs: 
            kubectlVersion: 1.15.0

        - task: AzureKeyVault@1
          displayName: Get secrets
          inputs:
            azureSubscription: '$(azureSubscription)'
            KeyVaultName: '$(keyVault)'
            SecretsFilter: 'servicePrincipalKey,vvpAPIToken,tenantId'

        - task: Bash@3
          inputs:
            filePath: 'azure-pipelines/setup-local-access.sh'
          env:
            servicePrincipal: $(servicePrincipal)
            servicePrincipalKey: $(servicePrincipalKey)
            tenantId: $(tenantId)
            resourceGroup: $(resourceGroup)
            kubernetesCluster: $(kubernetesCluster)
            kubernetesNamespace: $(kubernetesNamespace)
          displayName: Setup local access

        - task: Bash@3
          inputs:
            # this sets the 'jarFileName' variable
            filePath: 'azure-pipelines/extract-jar-filename.sh'
          displayName: Extract jar filename


        - task: Bash@3
          inputs:
            # this sets the 'deploymentId' variable
            filePath: 'azure-pipelines/find-deployment-id.sh'
          env:
            vvpNamespace: $(vvpNamespace)
            vvpAPIToken: $(vvpAPIToken)
            vvpJobJarPrefix: $(vvpJobJarPrefix)
          displayName: Check deployment

        - task: Bash@3
          inputs:
            filePath: 'azure-pipelines/patch-deployment.sh'
          env:
            deploymentId: $(deploymentId)
            vvpNamespace: $(vvpNamespace)
            vvpAPIToken: $(vvpAPIToken)
            jarFileName: $(jarFileName)
            blobContainer: $(blobContainer)
            storageAccount: $(storageAccount)
            buildVersion: $(Build.SourceVersion)
          condition: and(succeeded(), ne(variables['deploymentId'], '') )
          displayName: PATCH deployment

        - task: Bash@3
          inputs:
            filePath: 'azure-pipelines/post-deployment.sh'
          env:
            vvpNamespace: $(vvpNamespace)
            vvpAPIToken: $(vvpAPIToken)
            vvpDeploymentTarget: $(vvpDeploymentTarget)
            vvpJobJarPrefix: $(vvpJobJarPrefix)
            jarFileName: $(jarFileName)
            blobContainer: $(blobContainer)
            storageAccount: $(storageAccount)
            buildVersion: $(Build.SourceVersion)
          condition: and(succeeded(), eq(variables['deploymentId'], '') )
          displayName: POST deployment

# Monitor stage
- stage: Monitor
  displayName: Monitor stage
  dependsOn: Submit
  condition: succeeded()

  jobs:
    - job: Delay
      displayName: Delay a few minutes

      pool: server
 
      steps:
        - task: Delay@1  # requires 'pool: server'
          inputs:
            delayForMinutes: '$(delayMinutes)'

    - job: MonitorFlinkJob
      dependsOn: Delay

      pool:
        vmImage: $(vmImageName)

      steps:

        - task: KubectlInstaller@0
          displayName: Install kubectl
          inputs: 
            kubectlVersion: 1.15.0

        - task: AzureKeyVault@1
          displayName: Get secrets
          inputs:
            azureSubscription: '$(azureSubscription)'
            KeyVaultName: '$(keyVault)'
            SecretsFilter: 'servicePrincipalKey,vvpAPIToken,tenantId'

        - task: Bash@3
          inputs:
            filePath: 'azure-pipelines/setup-local-access.sh'
          env:
            servicePrincipal: $(servicePrincipal)
            servicePrincipalKey: $(servicePrincipalKey)
            tenantId: $(tenantId)
            resourceGroup: $(resourceGroup)
            kubernetesCluster: $(kubernetesCluster)
            kubernetesNamespace: $(kubernetesNamespace)
          displayName: Setup local access

        - task: Bash@3
          inputs:
            filePath: 'azure-pipelines/check-deployment.sh'
          env:
            vvpAPIToken: $(vvpAPIToken)
            vvpJobJarPrefix: $(vvpJobJarPrefix)
          displayName: Check job state
