trigger:
- master

variables:

  # Azure Resource Manager service connection 
  azureSubscription: 'vvp-pipeline-service-connection'

  # Agent VM image name: Windows is needed by AzureFileCopy@3
  vmImageName: 'windows-latest'

  # DEBUG
  system.debug: true

  # Ververica Platform related settings
  vvpResourceGroup: 'vvp-pipeline-demo'
  vvpClusterName: 'vvp-pipeline-cluster'
  vvpKubernetesNamespace: 'vvp'

  vvpNamespace: 'default'
  vvpDeploymentTarget: '6ebbe4f9-0377-462a-9112-81a2ef4ea0b5'
  servicePrincipal: 'http://vvp-pipeline-demo-service-principal'
  tenantId: '2925ee25-3bd0-402a-88f1-69307e6a39f3'
  keyVault: 'vvp-pipeline-keyvault'
  vvpJobJarPrefix: 'wiki-edits'
  vvpPipelineDemoStorage: 'vvppipelinestorage'
  vvpPipelineDemoBlobContainer: 'vvp-pipeline-artifacts'
  vvpDeploymentName: 'vvp-pipeline-demo-deployment'


stages:

### Build stage
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndPublish
    displayName: Package and publish

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: Stage job jar
      inputs:
        SourceFolder: 'target'
        Contents: '$(vvpJobJarPrefix)-*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)/artifacts'

    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: '$(build.artifactstagingdirectory)/artifacts'
        artifactName: JobJar

    # Passing variables cross stages is not supported in Azure Pipeline as of now
    # As a workaround: we publish it as an artifact then use it in another stage
    # Credits go to Alessandro Segala who mentioned this workaround here:
    # https://medium.com/microsoftazure/how-to-pass-variables-in-azure-pipelines-yaml-tasks-5c81c5d31763
    - bash: |
        mkdir -p $(build.artifactstagingdirectory)\variables
        cd '$(build.artifactstagingdirectory)\artifacts'
        ls $(vvpJobJarPrefix)-*.jar > ..\variables\artifactName
      displayName: Save artifact name

    - publish: $(build.artifactstagingdirectory)\variables
      artifact: variables
      displayName: Publish artifact name


### Deploy stage
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DownloadAndDeploy
      displayName: Download and deploy
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download artifacts
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(build.artifactstagingdirectory)/artifacts' 

      - task: AzureFileCopy@3
        displayName: Deploy to blob storage
        inputs:
          sourcePath: '$(build.artifactstagingdirectory)/artifacts' 
          azureSubscription: '$(azureSubscription)'
          destination: azureBlob
          storage: vvppipelinestorage
          containerName: vvp-pipeline-artifacts
          BlobPrefix: 'artifacts/namespaces/$(vvpNamespace)'

- stage: Submit
  displayName: Submit stage
  dependsOn: Deploy
  condition: succeeded()  
  jobs:
    - job: SubmitFlinkJob
      displayName: Submit flink job
      variables:
        artifactName: $[ dependencies.DownloadAndDeploy.outputs['extractArtifactName.artifactName'] ]

      steps:

        - bash: |
            commit=`echo $(Build.SourceVersion) | cut -c 1-7`
            echo "##vso[task.setvariable variable=commitHash]$commit"
          name: extractCommitHash

        - task: KubectlInstaller@0
          displayName: Install kubectl
          inputs: 
            kubectlVersion: 1.15.0

        - task: AzureKeyVault@1
          displayName: Get password
          inputs:
            azureSubscription: '$(azureSubscription)'
            KeyVaultName: '$(keyVault)'
            SecretsFilter: 'vvp-pipeline-demo-service-principal-password'

        # Here we download the artifact to get the artifactName
        - download: current
          artifact: variables

        - bash: |
            artifactName=$(cat $(Pipeline.Workspace)\variables\artifactName)
            echo "##vso[task.setvariable variable=artifactName]$artifactName"  

        - script: |
            az login --service-principal -u $(servicePrincipal) \
              -p $(vvp-pipeline-demo-service-principal-password) \
              --tenant $(tenantId)
          displayName: az login
        - script: |
            az aks get-credentials --resource-group $(vvpResourceGroup) \
              --name $(vvpClusterName)
          displayName: Get cluster credential
        - script: |
            kubectl port-forward service/vvp-ververica-platform 8080:80 \
              --namespace $(vvpKubernetesNamespace) &
          displayName: Port forward
        - script: |
            findDeploymentId=`curl -X GET "http://localhost:8080/api/v1/namespaces/$(vvpNamespace)/deployments" \
            -H "accept: application/json" -s \
            | python -c '
            import sys, json
            j=json.loads(sys.stdin.read())
            for i in j["items"]:
              if i["metadata"]["name"] == "$(vvpDeploymentName)":
                print i["metadata"]["id"]
            '`
            echo "##vso[task.setvariable variable=deploymentId]$findDeploymentId"
          displayName: Check deployment
        - script: |
            echo "PATCH Deployment $(deploymentId)"
            curl -X PATCH "http://localhost:8080/api/v1/namespaces/$(vvpNamespace)/deployments/$(deploymentId)" \
            -H "accept: application/yaml" -H "Content-Type: application/yaml" -s -d '
            kind: Deployment
            apiVersion: v1
            spec:
              state: RUNNING
              template:
                spec:
                  artifact:
                    jarUri: >-
                      wasbs://$(vvpPipelineDemoBlobContainer)@$(vvpPipelineDemoStorage).blob.core.windows.net/artifacts/namespaces/$(vvpNamespace)/$(artifactName)?commit=$(commitHash)
            '
          condition: ne(variables['deploymentId'], '')
          displayName: PATCH deployment
        - script: |
            curl -X POST "http://localhost:8080/api/v1/namespaces/$(vvpNamespace)/deployments" \
            -H "accept: application/yaml" -H "Content-Type: application/yaml" -s -d "
            kind: Deployment
            apiVersion: v1
            metadata:
              name: $(vvpDeploymentName)
              namespace: $(vvpNamespace)
            spec:
              state: RUNNING
              upgradeStrategy:
                kind: STATELESS
              restoreStrategy:
                kind: LATEST_SAVEPOINT
                allowNonRestoredState: false
              deploymentTargetId: $(vvpDeploymentTarget)
              template:
                metadata:
                  annotations: {}
                spec:
                  artifact:
                    kind: JAR
                    jarUri: >-
                      wasbs://$(vvpPipelineDemoBlobContainer)@$(vvpPipelineDemoStorage).blob.core.windows.net/artifacts/namespaces/$(vvpNamespace)/$(artifactName)?commit=$(commitHash)
                    flinkVersion: 1.9
                    flinkImageRegistry: registry.platform.data-artisans.net/v2.0
                    flinkImageRepository: flink
                    flinkImageTag: 1.9.1-stream1-scala_2.12
                  parallelism: 1
                  resources:
                    jobmanager:
                      cpu: 1
                      memory: 1G
                    taskmanager:
                      cpu: 1
                      memory: 2G
                  flinkConfiguration: {}
                  logging:
                    log4jLoggers: {}
            status:
              state: CANCELLED
            "
          condition: eq(variables['deploymentId'], '')
          displayName: POST deployment

