trigger:
- master

variables:

  # Azure Resource Manager service connection 
  azureSubscription: 'vvp-pipeline-service-connection'

  # Agent VM image name: Windows is needed by AzureFileCopy@3
  vmImageName: 'windows-latest'

  # DEBUG
  system.debug: true

  # Ververica Platform related settings
  vvpNamespace: 'default'
  vvpDeploymentTarget: ''

stages:

### Build stage
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndPublish
    displayName: Package and Publish

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: Stage job jar
      inputs:
        SourceFolder: 'target'
        Contents: 'wiki-*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifactName: JobJar

### Deploy stage
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: DownloadAndDeploy
      displayName: Download and deploy
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download artifacts
        inputs:
          artifact: 'JobJar'
          downloadPath: '$(build.artifactstagingdirectory)' 

      - task: AzureFileCopy@3
        displayName: Deploy to blob storage
        inputs:
          sourcePath: '$(build.artifactstagingdirectory)' 
          azureSubscription: '$(azureSubscription)'
          destination: azureBlob
          storage: vvppipelinestorage
          containerName: vvp-pipeline-artifacts
          BlobPrefix: 'artifacts/namespaces/$(vvpNamespace)'
          